# Generated by Django 4.0.3 on 2022-03-26 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Post',
            new_name='New',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='commentPost',
            new_name='commentNew',
        ),
        migrations.RenameField(
            model_name='new',
            old_name='postCategory',
            new_name='newCategory',
        ),
    ]
