# Generated by Django 4.0.3 on 2022-03-28 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_rename_post_new_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='new',
            name='dateCreation',
            field=models.DateField(auto_now_add=True, verbose_name='дата публикации'),
        ),
    ]
