# Generated by Django 4.0.3 on 2022-04-13 20:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0006_rename_subscriber_categorytouser_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='categorytouser',
            old_name='user',
            new_name='subscribers',
        ),
    ]
